
storage_path: "./storage/storage.db"
http_server:
  port: ":8080"
postgresql:
  user: "admin"
  password: "secretpass"
  host: "localhost"
  port: "5432"
  dbname: "products"
kafka:
  broker: "localhost:9092"
  topic: "orders"